CREATE TABLE IF NOT EXISTS users(
    id VARCHAR(128) NOT NULL UNIQUE,
    username VARCHAR(254) UNIQUE,
    email VARCHAR(254) NOT NULL UNIQUE,
    display_name VARCHAR(512) DEFAULT '',
    password VARCHAR(1024) NOT NULL,
    salt VARCHAR(512) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source VARCHAR(128) DEFAULT '',

    PRIMARY KEY(id));

CREATE TABLE IF NOT EXISTS tokens(
    id VARCHAR(128) NOT NULL UNIQUE,
    user_id VARCHAR(128) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY(user_id) REFERENCES users(id),
    PRIMARY KEY(id));

CREATE TABLE IF NOT EXISTS shares(
    id VARCHAR(128) NOT NULL UNIQUE,
    owner_id VARCHAR(128) NOT NULL,
    file_path VARCHAR(256) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP,
    readonly BOOLEAN NOT NULL DEFAULT FALSE,
    receiver_user_id VARCHAR(128),
    receiver_email VARCHAR(128),

    FOREIGN KEY(receiver_user_id) REFERENCES users(id),
    FOREIGN KEY(owner_id) REFERENCES users(id),
    PRIMARY KEY(id));
